#!/usr/bin/env python3
"""
SeedMediaDatabase.py

Loads the one-time export from server 2 into the mediamixer database on
server 3. Runs on server 3, against the media database only. Server 2 is
not contacted and is not modified — it was read once, by
ExportFromServer2.sh, and is done.

What actually matters here is the human tagging: place_name,
hook_compatibility, notes, type/subtype/category/subcategory, cityid, and
the assigned asset_id. Everything else in the table can be regenerated by
re-running the inventory against S3. That tagging cannot.

Two details are easy to get wrong and both are handled:

  Original id values are carried over, because asset_id is derived from id
  ('UGC-' || lpad(id, 5, '0')). Letting ids be reassigned would leave
  UGC-00007 sitting on row 12, permanently confusing.

  The sequence is therefore stale after loading and is reset. Skipping that
  is the classic follow-on bug: the next insert fails on a duplicate key.

Imported rows land in status='discovered' with rights_status='unknown'
regardless of how completely they were tagged. The semantics are
trustworthy; the technical facts do not exist yet — no row has a checksum,
dimensions, or a rights decision. The import carries tagging forward, it
does not shortcut the review gate.

Usage:
    python3 SeedMediaDatabase.py --export-dir ~/mediamixer-export-20260726 --dry-run
    python3 SeedMediaDatabase.py --export-dir ~/mediamixer-export-20260726
    python3 SeedMediaDatabase.py --export-dir ... --cities-only

Env (from the systemd EnvironmentFile in the .service, or ./.env locally):
    DATABASE_URL  — required; the mediamixer database on server 3
"""

import argparse
import csv
import glob
import os
import sys
from urllib.parse import urlparse, unquote

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from PostgresInterpreter import PostgresInterpreter  # noqa: E402

ASSET_COLUMNS = [
    "id", "asset_id", "s3_key", "filename", "folder", "place_name", "cityid",
    "country", "type", "subtype", "category", "subcategory",
    "hook_compatibility", "notes", "duration", "size_bytes", "content_type",
    "created_at", "updated_at",
]

CITY_COLUMNS = ["cityid", "cityname", "country", "city_slug"]

ASSET_TYPE_FROM_LEGACY = {
    "b-roll": "broll", "broll": "broll", "app": "app", "reaction": "reaction",
    "music": "music", "voiceover": "voiceover", "caption": "caption", "cta": "cta",
}


def load_env_file(path=".env"):
    if not os.path.exists(path):
        return
    with open(path, "r", encoding="utf-8") as handle:
        for line in handle:
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            key, value = line.split("=", 1)
            os.environ.setdefault(key.strip(), value.strip().strip('"').strip("'"))


def parse_database_url(database_url):
    database_url = database_url.replace("postgresql+asyncpg://", "postgresql://")
    u = urlparse(database_url)
    if u.scheme not in ("postgresql", "postgres"):
        raise ValueError(f"Unsupported DB scheme: {u.scheme}")
    user = u.username or ""
    password = unquote(u.password or "")
    database = (u.path or "").lstrip("/")
    if not user or not database:
        raise ValueError(f"Could not parse user/database from DATABASE_URL: {database_url}")
    return {"user": user, "password": password, "host": u.hostname or "127.0.0.1",
            "port": str(u.port or 5432), "database": database}


def find_one(export_dir, pattern):
    matches = sorted(glob.glob(os.path.join(export_dir, pattern)))
    if not matches:
        return None
    if len(matches) > 1:
        print(f"[WARN] {len(matches)} files match {pattern}; using {matches[-1]}")
    return matches[-1]


def read_csv(path, expected_columns):
    with open(path, newline="", encoding="utf-8") as handle:
        reader = csv.DictReader(handle)
        missing = [c for c in expected_columns if c not in (reader.fieldnames or [])]
        if missing:
            raise SystemExit(f"{path} is missing columns: {', '.join(missing)}")
        return list(reader)


def blank_to_none(value):
    return None if value == "" else value


def parse_pg_array(value):
    """
    Turns PostgreSQL's CSV array form — {"Best Pizza","Hidden Gems"} — back
    into a list. This is the field most likely to be corrupted by a CSV
    round-trip, which is why the loader verifies element counts afterward.
    """
    if value in (None, "", "{}"):
        return None
    inner = value.strip()
    if inner.startswith("{") and inner.endswith("}"):
        inner = inner[1:-1]
    if not inner:
        return None
    items, current, in_quotes, escaped = [], [], False, False
    for char in inner:
        if escaped:
            current.append(char)
            escaped = False
        elif char == "\\":
            escaped = True
        elif char == '"':
            in_quotes = not in_quotes
        elif char == "," and not in_quotes:
            items.append("".join(current).strip())
            current = []
        else:
            current.append(char)
    items.append("".join(current).strip())
    return [i for i in items if i] or None


def seed_cities(db, rows, dry_run):
    if dry_run:
        return len(rows)
    for row in rows:
        db.execute_query("""
            INSERT INTO public.cities_reference (cityid, cityname, country, city_slug, refreshed_at)
            VALUES (%s, %s, %s, %s, now())
            ON CONFLICT (cityid) DO UPDATE SET
                cityname = EXCLUDED.cityname,
                country = EXCLUDED.country,
                city_slug = EXCLUDED.city_slug,
                refreshed_at = now()
        """, (row["cityid"], blank_to_none(row.get("cityname")),
              blank_to_none(row.get("country")), blank_to_none(row.get("city_slug"))))
    return len(rows)


INSERT_ASSET_SQL = """
INSERT INTO public.content_library_assets (
    id, asset_id, bucket_name, s3_key, filename, folder, place_name,
    cityid, country, type, asset_type, subtype, category, subcategory,
    hook_compatibility, notes, duration, size_bytes, content_type,
    status, rights_status, first_seen_at, last_seen_at,
    created_at, updated_at
) VALUES (
    %(id)s, %(asset_id)s, %(bucket)s, %(s3_key)s, %(filename)s, %(folder)s,
    %(place_name)s, %(cityid)s, %(country)s, %(type)s, %(asset_type)s,
    %(subtype)s, %(category)s, %(subcategory)s, %(hook_compatibility)s,
    %(notes)s, %(duration)s, %(size_bytes)s, %(content_type)s,
    'discovered', 'unknown', %(created_at)s, %(created_at)s,
    %(created_at)s, %(updated_at)s
)
ON CONFLICT (bucket_name, s3_key) DO NOTHING
"""


def seed_assets(db, rows, bucket, dry_run):
    loaded = skipped = 0
    for row in rows:
        legacy_type = blank_to_none(row.get("type"))
        params = {
            "id": int(row["id"]),
            "asset_id": blank_to_none(row.get("asset_id")),
            "bucket": bucket,
            "s3_key": row["s3_key"],
            "filename": blank_to_none(row.get("filename")),
            "folder": blank_to_none(row.get("folder")),
            "place_name": blank_to_none(row.get("place_name")),
            "cityid": blank_to_none(row.get("cityid")),
            "country": blank_to_none(row.get("country")),
            "type": legacy_type,
            "asset_type": ASSET_TYPE_FROM_LEGACY.get(
                (legacy_type or "").strip().lower()),
            "subtype": blank_to_none(row.get("subtype")),
            "category": blank_to_none(row.get("category")),
            "subcategory": blank_to_none(row.get("subcategory")),
            "hook_compatibility": parse_pg_array(row.get("hook_compatibility")),
            "notes": blank_to_none(row.get("notes")),
            "duration": blank_to_none(row.get("duration")),
            "size_bytes": blank_to_none(row.get("size_bytes")),
            "content_type": blank_to_none(row.get("content_type")),
            "created_at": blank_to_none(row.get("created_at")),
            "updated_at": blank_to_none(row.get("updated_at")),
        }
        if dry_run:
            loaded += 1
            continue
        if db.execute_query(INSERT_ASSET_SQL, params) is False:
            skipped += 1
            print(f"[ERROR] failed to load {row['s3_key']}")
        else:
            loaded += 1
    return loaded, skipped


def reset_sequence(db):
    """
    Explicit ids were carried over, so the sequence still points at 1 and
    the next insert would collide. Not optional.
    """
    db.execute_query("""
        SELECT setval(
            pg_get_serial_sequence('public.content_library_assets', 'id'),
            GREATEST(COALESCE((SELECT max(id) FROM public.content_library_assets), 1), 1)
        )
    """)
    db.connection.commit()


def verify(db, source_rows, bucket):
    rows = db.execute_query("""
        SELECT count(*), count(place_name), count(hook_compatibility),
               count(notes), count(asset_id), coalesce(max(id), 0)
        FROM public.content_library_assets WHERE bucket_name = %s
    """, (bucket,))
    if not rows:
        return None
    loaded = dict(zip(
        ["rows", "place_name", "hooks", "notes", "asset_id", "max_id"], rows[0]))

    expected = {
        "rows": len(source_rows),
        "place_name": sum(1 for r in source_rows if blank_to_none(r.get("place_name"))),
        "hooks": sum(1 for r in source_rows if parse_pg_array(r.get("hook_compatibility"))),
        "notes": sum(1 for r in source_rows if blank_to_none(r.get("notes"))),
        "asset_id": sum(1 for r in source_rows if blank_to_none(r.get("asset_id"))),
        "max_id": max((int(r["id"]) for r in source_rows), default=0),
    }

    # pg_get_serial_sequence returns text, so the cast belongs on the
    # function argument, not on a FROM item.
    seq = db.execute_query("""
        SELECT pg_sequence_last_value(
            pg_get_serial_sequence('public.content_library_assets', 'id')::regclass)
    """)
    return loaded, expected, (seq[0][0] if seq and seq[0][0] is not None else None)


def main():
    ap = argparse.ArgumentParser(
        description="Seed the mediamixer database from the server 2 export.")
    ap.add_argument("--export-dir", required=True,
                    help="Directory produced by ExportFromServer2.sh")
    ap.add_argument("--dry-run", action="store_true",
                    help="Parse and verify the export, write nothing")
    ap.add_argument("--cities-only", action="store_true",
                    help="Refresh cities_reference only")
    ap.add_argument("--bucket", default=os.getenv(
        "CLIPS_BUCKET", "big-city-travel-guide-clips"))
    args = ap.parse_args()

    load_env_file()
    database_url = os.getenv("DATABASE_URL")
    if not database_url:
        raise SystemExit("DATABASE_URL is not set.")

    mode = "DRY-RUN" if args.dry_run else "LIVE"
    prefix = "Would be " if args.dry_run else ""
    print(f"[SEED] mode={mode}  export={args.export_dir}")

    cities_csv = find_one(args.export_dir, "cities_reference_*.csv")
    assets_csv = find_one(args.export_dir, "content_library_assets_*.csv")
    if cities_csv is None:
        raise SystemExit(f"No cities_reference_*.csv in {args.export_dir}")
    if assets_csv is None and not args.cities_only:
        raise SystemExit(f"No content_library_assets_*.csv in {args.export_dir}")

    city_rows = read_csv(cities_csv, CITY_COLUMNS)
    asset_rows = [] if args.cities_only else read_csv(assets_csv, ASSET_COLUMNS)
    print(f"[SEED] cities={len(city_rows)}  assets={len(asset_rows)}")

    db = PostgresInterpreter(**parse_database_url(database_url))
    with db:
        if not db.connection:
            raise SystemExit("Could not connect to the database.")

        seeded_cities = seed_cities(db, city_rows, args.dry_run)
        print(f"  {prefix}cities_reference rows: {seeded_cities}")

        if not args.cities_only:
            loaded, skipped = seed_assets(db, asset_rows, args.bucket, args.dry_run)
            print(f"  {prefix}assets loaded: {loaded}  failed: {skipped}")

            if not args.dry_run:
                reset_sequence(db)
                result = verify(db, asset_rows, args.bucket)
                if result:
                    got, expected, sequence = result
                    print("\n[VERIFY] loaded vs source")
                    ok = True
                    for field in ("rows", "place_name", "hooks", "notes",
                                  "asset_id", "max_id"):
                        match = got[field] == expected[field]
                        ok = ok and match
                        print(f"  {'ok  ' if match else 'FAIL'} {field:<12} "
                              f"loaded={got[field]}  source={expected[field]}")
                    seq_ok = sequence is not None and sequence >= expected["max_id"]
                    ok = ok and seq_ok
                    print(f"  {'ok  ' if seq_ok else 'FAIL'} {'sequence':<12} "
                          f"value={sequence}  max_id={expected['max_id']}")
                    print("\n" + ("[VERIFY] all checks passed" if ok else
                                  "[VERIFY] MISMATCH — do not cut over yet"))

    if args.dry_run:
        print("\nNo database changes were made.")


if __name__ == "__main__":
    main()
